#+title: Fedora
* Enable hibernation
Note that this may be unnecessary! The fedora install on my workstation had
working swap/hibernate OOTB (using systemd ~swap.target~).
** Find swap partition
#+NAME: swap_uuid
#+begin_src shell :results output
swap_partition=($(sudo lsblk --list --noheadings -o NAME,UUID,FSTYPE | awk '$3 == "swap" { print $1, $2 }'))
echo "Setting up swap/hibernate on ${swap_partition[0]} UUID=${swap_partition[1]}" >&2
echo ${swap_partition[1]}
#+end_src
** Add to ~/etc/fstab~
#+BEGIN_SRC shell :var SWAP_UUID=swap_uuid
# Check if /etc/fstab contains a line with UUID=$SWAP_UUID
if grep -q "UUID=$SWAP_UUID" /etc/fstab; then
    echo "UUID=$SWAP_UUID entry already exists in /etc/fstab."
else
    # If not, append "UUID=$SWAP_UUID none swap sw 0 0"
    echo "UUID=$SWAP_UUID none swap sw 0 0" | sudo tee -a /etc/fstab
    echo "Added UUID=$SWAP_UUID entry to /etc/fstab."
fi
** Add resume module to dracut
#+begin_src shell
sudo tee /etc/dracut.conf.d/10_resume.conf <<EOF
# Enable Hibernation (via resume module)
add_dracutmodules+=" resume "
EOF
#+end_src
** Rebuild initramfs
#+begin_src shell
sudo dracut -f
#+end_src
* Set-up nonfree Repos ([[https://docs.fedoraproject.org/en-US/quick-docs/rpmfusion-setup/][Enabling the RPM Fusion repositories :: Fedora Docs]])
- Codecs are required to play any videos. YouTube in Firefox will not work without this
- NVIDIA drivers are useful
** Load the repos
#+begin_src shell
sudo dnf install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf update -y
#+end_src
** Install FFmpeg with nonfree codecs so that firefox can play video
Note that we have to install this instead of the previously installed "free"
ffmpeg, so we need ~--allowerasing~.
#+begin_src shell
sudo dnf install --allowerasing ffmpeg
#+end_src
** "Enable AppStream"
#+begin_src shell
sudo dnf group update core
#+end_src
* Cleanup
- Don't use DNF to install PyCharm. This is bad because
  + old versions
  + "unoffical" approach
- Also we have JetBrains Toolbox, infinitely more convenient
#+begin_src shell
sudo dnf config-manager --set-disabled copr:copr.fedorainfracloud.org:phracek:PyCharm
#+end_src
* NVIDIA? :optional:
- OpenGL/DRM
- Cuda
- Accelerated video decode
#+begin_src shell
sudo dnf install akmod-nvidia vulkan xorg-x11-drv-nvidia-cuda nvidia-vaapi-driver libva-utils vdpauinfo
#+end_src
* Install basic packages
#+begin_src shell
sudo dnf install keepassxc emacs neovim ripgrep graphviz
#+end_src
* Install useful apps
#+begin_src shell
sudo dnf install kgraphviewer cantor maxima maxima-runtime-sbcl thunderbird okular filelight
#+end_src
* Install LaTeX :optional:
#+begin_src shell
sudo dnf install texlive-scheme-full
#+end_src
* Migrate from GNOME to KDE :optional:
** Install KDE
#+begin_src shell
sudo dnf groupinstall "KDE Plasma Workspaces"
#+end_src
** COMMENT (outdated) Set as default desktop
#+begin_src shell
echo "DESKTOP=KDE" | sudo tee /etc/sysconfig/desktop
#+end_src
** Use SDDM
#+begin_src shell
sudo systemctl disable gdm
sudo systemctl enable sddm
#+end_src
